-- This script creates the database structure (the tables).

-- Create the ARTIST table
CREATE TABLE "ARTIST" (
	"ARTIST_ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT NOT NULL,
	"FAMILY_NAME"	TEXT,
	"ORIGIN"	TEXT,
	PRIMARY KEY("ARTIST_ID" AUTOINCREMENT)
);

-- Create the SOLD_ALBUMS table
CREATE TABLE "SOLD_ALBUMS" (
	"ARTIST_ID"	INTEGER,
	"SOLD_ALBUMS"	INTEGER,
	"NOTES"	TEXT,
	FOREIGN KEY("ARTIST_ID") REFERENCES "ARTIST"("ARTIST_ID")
);